name: ğŸš‚ Main

on:
  push:
    branches:
      "**"

jobs: 
  ci:
    name: ğŸ’š CI 
    uses: ./.github/workflows/ci.yaml

  build:
    name: ğŸ—ï¸ Build
    uses: ./.github/workflows/build.yaml
    needs: ci

  deploy:
    name: ğŸš€ Deploy
    uses: ./.github/workflows/deploy.yaml
    needs: build
